name: Build and Deploy to S3

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout#usage
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env file
        working-directory: ./next-app
        run: |
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
