name: Build and Deploy to S3

on:
  push:
    branches:
      - develop
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies and Build
        working-directory: ./app
        run: |
          npm install
          npm run build

      - name: Deploy to Dev
        if: contains(toJSON(github.ref), 'develop')
        run: |
          aws s3 cp --recursive ./app/public ${{ secrets.AWS_S3_BUCKET_DEV_URI }}

      - name: Deploy to Prod
        if: contains(toJSON(github.ref), 'master')
        run: |
          aws s3 cp --recursive ./app/public ${{ secrets.AWS_S3_BUCKET_PROD_URI }}
