name: Build and Deploy to S3
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies and Build
        working-directory: ./app
        run: |
          npm install
          npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_URI: ${{ secrets.S3_URI }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 cp --recursive ./app/public $S3_URI
